// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnjczrajqnazceetytfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduamN6cmFqcW5hemNlZXR5dGZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTE0MTYsImV4cCI6MjA2NzkyNzQxNn0.xZ4jg8Gql36UlN1Etqe1Y3GVLvfhZL3cm4WCjHUc9mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});