---
receive_query_task:
  description: Accept the user's query to analyze {policy_name} and delegate the task
    to the Policy Discovery Agent.
  expected_output: The query is delegated to the Policy Discovery Agent.
  async_execution: false
  agent: coordinator_agent
fetch_policy_text_task:
  description: Use SerperDevTool and ScrapeWebsiteTool to retrieve the raw text of
    the specified policy {policy_name}.
  expected_output: The raw text of the policy {policy_name} is retrieved.
  async_execution: false
  agent: policy_discovery_agent
analyze_policy_text_task:
  description: Identify primary stakeholders in the policy {policy_name} and create
    sub-agents for the top stakeholders.
  expected_output: Primary stakeholders are identified and sub-agents are created
    for them.
  async_execution: false
  agent: policy_debate_agent
  context:
  - fetch_policy_text_task
dynamic_sub_agent_creation_task:
  description: Instantiate Advocate Sub-Agents for each stakeholder to analyze the
    policy {policy_name}.
  expected_output: Advocate Sub-Agents are created and ready to analyze the policy.
  async_execution: false
  agent: policy_debate_agent
  context:
  - analyze_policy_text_task
stakeholder_analysis_task:
  description: Each sub-agent analyzes the policy {policy_name} from their perspective
    and generates key arguments.
  expected_output: Key arguments from each stakeholder perspective are generated.
  async_execution: false
  agent: advocate_sub_agents
  context:
  - dynamic_sub_agent_creation_task
synthesize_summary_task:
  description: Collect arguments from sub-agents and create a balanced summary of
    the policy {policy_name}.
  expected_output: A balanced summary of the policy {policy_name} is created.
  async_execution: false
  agent: action_agent
  context:
  - stakeholder_analysis_task
draft_email_task:
  description: Use the summary to draft an email for the user regarding the policy
    {policy_name}.
  expected_output: An email draft summarizing the policy {policy_name} is created
    for the user.
  async_execution: false
  agent: action_agent
  context:
  - synthesize_summary_task
